public inherited sharing class Constants {
//Errors
    public static final String ERROR_FLIGHT_DEPARTED = 'The flight departed';
    public static final String ERROR_YOUNG_AGE = 'The tourist is so young';
//Exceptions
    public static final String FIRST_CUSTOM_EXCEPTION = 'First exception';
    public static final String FINALLY_OK_CUSTOM_EXCEPTION = 'All right! Not any mistakes :)';
//Nums
    public static final Decimal AVERAGE_DAYS_IN_YEAR = 365.25;
//Messages
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String FLIGHT_REPORT = 'Deleted flight report';
    public static final String EMAIL_MESSAGE_DEL_FLIGHTS = 'Information about tourists and counters deleted flights - ';
}