public inherited sharing class Constants {
//Errors
    public static final String ERROR_FLIGHT_DEPARTED = 'The flight departed';
    public static final String ERROR_YOUNG_AGE = 'The tourist is so young';
//Exceptions
    public static final String FIRST_CUSTOM_EXCEPTION = 'First exception';
    public static final String FINALLY_OK_CUSTOM_EXCEPTION = 'All right! Not any mistakes :)';
    public static final String FINALLY_EXCEPTIONS_HAPPENED = 'The following exception has occurred: ';
//Nums
    public static final Decimal AVERAGE_DAYS_IN_YEAR = 365.25;
//Messages
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String FLIGHT_REPORT = 'Deleted flight report';
    public static final String EMAIL_MESSAGE_DEL_FLIGHTS = 'Information about tourists and counters deleted flights - ';
//Scheduler
    public static final String EVERY_HOUR_FROM_00MIN = '0 0 * * * ?';
    public static final String EVERY_HOUR_FROM_30MIN = '0 30 * * * ?';
//HTTP
	public static final String HTTP_METHOD_GET = 'GET';
    public static final String HTTP_METHOD_POST = 'POST';
    public static final Integer HTTP_STATUS_CODE_200 = 200;
    public static final Integer HTTP_STATUS_CODE_404 = 404;    
    public static final Integer HTTP_STATUS_CODE_500 = 500;
}